/**
 * Car catalog seed data
 * ---------------------------------------------------------------------------
 * The same nine cars the frontend prototype shipped with. On first boot the
 * CatalogSeeder inserts them so the catalog is never empty; after that MongoDB
 * is the source of truth. These are typed as domain `Car`s (minus the db-managed
 * fields) so they flow straight through the CarRepository port.
 */
import type { Car } from '../../../../core/domain/entities/car';
import { CarStatus } from '../../../../core/domain/entities/car';

export type CarSeed = Omit<Car, '_id' | 'createdAt' | 'updatedAt'>;

export const CARS_SEED: CarSeed[] = [
  {
    slug: 'byd-song-plus-2021',
    title: '2021 BYD Song PLUS EV · Flagship',
    make: 'BYD',
    fuel: 'Electric',
    km: '38,420 km',
    firstReg: 'First reg 03/2021',
    city: 'Guangzhou',
    image: 'byd-song-plus.jpg',
    credit: 'Nikolai Bulykin / Wikimedia Commons / CC BY-SA 4.0',
    history: [
      { tone: 'ok', text: '0 accidents' },
      { tone: 'warn', text: '1 claim' },
    ],
    source: 'via che300',
    price: '₦24,480,000',
    priceNote: 'Live rate · illustrative',
    status: CarStatus.AVAILABLE,
  },
  {
    slug: 'tesla-model3-2022',
    title: '2022 Tesla Model 3 · Standard Range',
    make: 'Tesla',
    fuel: 'Electric',
    km: '29,100 km',
    firstReg: 'First reg 06/2022',
    city: 'Shanghai',
    image: 'tesla-model3.jpg',
    credit: 'Alexander-93 / Wikimedia Commons / CC BY-SA 4.0',
    history: [
      { tone: 'ok', text: '0 accidents' },
      { tone: 'ok', text: '0 claims' },
    ],
    source: 'via che300',
    price: '₦31,200,000',
    priceNote: 'Live rate · illustrative',
    status: CarStatus.AVAILABLE,
  },
  {
    slug: 'gac-aion-s-2021',
    title: '2021 GAC Aion S · Plus',
    make: 'GAC',
    fuel: 'Electric',
    km: '41,300 km',
    firstReg: 'First reg 09/2021',
    city: 'Guangzhou',
    image: 'gac-aion-s.jpg',
    credit: 'Jengtingchen / Wikimedia Commons / CC BY-SA 4.0',
    history: [
      { tone: 'ok', text: '0 accidents' },
      { tone: 'warn', text: '1 claim' },
    ],
    source: 'via che300',
    price: '₦16,800,000',
    priceNote: 'Another buyer is inspecting',
    status: CarStatus.HOLD,
  },
  {
    slug: 'byd-han-2020',
    title: '2020 BYD Han EV · Premium',
    make: 'BYD',
    fuel: 'Electric',
    km: '52,800 km',
    firstReg: 'First reg 11/2020',
    city: 'Shenzhen',
    image: 'byd-han.jpg',
    credit: 'Jengtingchen / Wikimedia Commons / CC BY-SA 4.0',
    history: [
      { tone: 'ok', text: '0 accidents' },
      { tone: 'ok', text: '5 service records' },
    ],
    source: 'via che300',
    price: '₦22,900,000',
    priceNote: 'Live rate · illustrative',
    status: CarStatus.AVAILABLE,
  },
  {
    slug: 'li-auto-one-2022',
    title: '2022 Li Auto ONE · 6-seat',
    make: 'Li Auto',
    fuel: 'Hybrid · EREV',
    km: '47,600 km',
    firstReg: 'First reg 04/2022',
    city: 'Beijing',
    image: 'li-auto-one.jpg',
    credit: 'Jengtingchen / Wikimedia Commons / CC BY-SA 4.0',
    history: [
      { tone: 'ok', text: '0 accidents' },
      { tone: 'ok', text: '0 claims' },
    ],
    source: 'via che300',
    price: '₦38,500,000',
    priceNote: 'Live rate · illustrative',
    status: CarStatus.AVAILABLE,
  },
  {
    slug: 'geely-coolray-2019',
    title: '2019 Geely Coolray · Sport',
    make: 'Geely',
    fuel: 'Petrol',
    km: '61,200 km',
    firstReg: 'First reg 08/2019',
    city: 'Ningbo',
    image: 'geely-coolray.jpg',
    credit: 'Юрий Д.К. / Wikimedia Commons / CC BY 4.0',
    history: [
      { tone: 'ok', text: '0 accidents' },
      { tone: 'warn', text: '1 claim' },
      { tone: 'ok', text: '4 service' },
    ],
    source: '',
    price: '₦14,200,000',
    priceNote: 'Live rate · illustrative',
    status: CarStatus.AVAILABLE,
  },
  {
    slug: 'nio-es6-2021',
    title: '2021 NIO ES6 · Performance',
    make: 'NIO',
    fuel: 'Electric',
    km: '44,900 km',
    firstReg: 'First reg 02/2021',
    city: 'Hefei',
    image: 'nio-es6.jpg',
    credit: 'JustAnotherCarDesigner / Wikimedia Commons / CC BY-SA 4.0',
    history: [
      { tone: 'ok', text: '0 accidents' },
      { tone: 'ok', text: '0 claims' },
    ],
    source: 'via che300',
    price: '₦28,700,000',
    priceNote: 'Live rate · illustrative',
    status: CarStatus.AVAILABLE,
  },
  {
    slug: 'changan-uni-t-2022',
    title: '2022 Changan UNI-T · Tech',
    make: 'Changan',
    fuel: 'Petrol',
    km: '33,500 km',
    firstReg: 'First reg 05/2022',
    city: 'Chongqing',
    image: 'changan-uni-t.jpg',
    credit: 'Jengtingchen / Wikimedia Commons / CC BY-SA 4.0',
    history: [
      { tone: 'ok', text: '0 accidents' },
      { tone: 'ok', text: '2 service' },
    ],
    source: 'via che300',
    price: '₦15,600,000',
    priceNote: 'Live rate · illustrative',
    status: CarStatus.AVAILABLE,
  },
  {
    slug: 'byd-dolphin-2023',
    title: '2023 BYD Dolphin · Comfort',
    make: 'BYD',
    fuel: 'Electric',
    km: '18,200 km',
    firstReg: 'First reg 01/2023',
    city: "Xi'an",
    image: 'byd-dolphin.jpg',
    credit: 'Alexander-93 / Wikimedia Commons / CC BY-SA 4.0',
    history: [
      { tone: 'ok', text: '0 accidents' },
      { tone: 'ok', text: '0 claims' },
    ],
    source: 'via che300',
    price: '₦19,400,000',
    priceNote: 'Live rate · illustrative',
    status: CarStatus.AVAILABLE,
  },
];
